26.(1) Створіть одновимірний масив (вектор) з оберненими значеннями факторіалів
натуральних чисел, починаючи з 1, та виведіть його значення.

In [1]:
import numpy as np
from math import factorial

# Визначаємо кількість елементів у векторі
n = 10  # Наприклад, перші 10 факторіалів

# Створюємо масив з оберненими значеннями факторіалів
vector = np.array([1/factorial(i) for i in range(1, n+1)])

# Виводимо значення вектора
print(vector)

[1.00000000e+00 5.00000000e-01 1.66666667e-01 4.16666667e-02
 8.33333333e-03 1.38888889e-03 1.98412698e-04 2.48015873e-05
 2.75573192e-06 2.75573192e-07]


Висновок до завдання:
У процесі виконання завдання ми створили одновимірний масив (вектор), що містить обернені значення факторіалів натуральних чисел, починаючи з 1. Для цього було використано мову програмування Python та бібліотеку NumPy, що дозволило ефективно обчислити факторіали та їхні обернені значення. Отриманий вектор демонструє експоненційне зменшення значень з кожним наступним числом, що відображає швидке зростання факторіалів. Цей підхід може бути корисним у різних математичних і статистичних задачах, де необхідно працювати з оберненими значеннями факторіалів.

26.(2)Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його квадратами 
факторіалів кожного числа, починаючи з 1, та виведіть його значення

In [1]:
import numpy as np
from math import factorial

# Створення масиву
matrix = np.zeros((3, 3), dtype=np.int64)

# Заповнення матриці квадратами факторіалів чисел
for i in range(3):
    for j in range(3):
        number = 3 * i + j + 1  # обчислення числа для позиції [i, j]
        matrix[i, j] = factorial(number) ** 2

# Виведення матриці
print(matrix)


[[           1            4           36]
 [         576        14400       518400]
 [    25401600   1625702400 131681894400]]


Висновок:
У цьому завданні ми створили двовимірний масив (матрицю) розміром 3x3, заповнений квадратами факторіалів натуральних чисел, починаючи з 1. Для цього ми використали мову програмування Python та бібліотеку NumPy.Отримана матриця продемонструвала значний ріст значень, що відображає експоненційне збільшення факторіалів чисел і відповідне зростання їх квадратів. Це завдання допомогло закріпити навички роботи з двовимірними масивами, а також продемонструвало основи лінійної алгебри в контексті факторіалів та їх властивостей.

26.(3)Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 
1 до 10 та знайдіть мін елемент.

In [2]:
import numpy as np

# Створення масиву з випадковими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Знаходження мінімального елемента
min_element = np.min(matrix)

# Виведення масиву та мінімального елемента
print("Матриця:")
print(matrix)
print("\nМінімальний елемент:", min_element)


Матриця:
[[2 4 7]
 [9 6 9]
 [8 1 6]]

Мінімальний елемент: 1


Висновок:
У цьому завданні ми створили двовимірний масив (матрицю) розміром 3x3, заповнений випадковими натуральними числами в діапазоні від 1 до 10. Далі ми успішно знайшли мінімальний елемент у створеній матриці.

26.(4)Створіть масив розміром 2x2, заповніть його випадковими дійсними числами від -1.2 
до 1.2 та виведіть його значення.

In [3]:
import numpy as np

# Створення масиву 2x2 з випадковими дійсними числами від -1.2 до 1.2
array = np.random.uniform(-1.2, 1.2, (2, 2))

# Виведення значення масиву
print(array)


[[-0.60491868 -0.91062514]
 [ 0.93098732  0.66159995]]


Висновок: у цьому завданні ми створили двовимірний масив розміром 2x2 та заповнили його випадковими дійсними числами в діапазоні від -1.2 до 1.2. Для цього було використано функцію np.random.uniform, яка дозволяє генерувати випадкові числа в заданому діапазоні. Результат показує, що масив складається з дійсних чисел, які випадково розподілені в межах заданих значень. Цей підхід можна використовувати для ініціалізації масивів у задачах, де важливо мати випадкові числа в певному діапазоні.

26.(5)Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими  
числами в діапазоні від 20 до 30 та виконайте на них поелементні операції додавання,  
віднімання та множення.

In [4]:
import numpy as np

# Створюємо два одновимірних масиви розміром 5 з випадковими цілими числами від 20 до 30
array1 = np.random.randint(20, 31, size=5)
array2 = np.random.randint(20, 31, size=5)

# Виводимо масиви
print("Array 1:", array1)
print("Array 2:", array2)

# Виконуємо поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Array 1: [30 25 29 27 22]
Array 2: [21 21 24 25 30]
Addition: [51 46 53 52 52]
Subtraction: [ 9  4  5  2 -8]
Multiplication: [630 525 696 675 660]


Висновок:
У рамках виконання завдання ми створили два одновимірних масиви, кожен з яких містить 5 випадкових цілих чисел в діапазоні від 20 до 30.В результаті виконання поелементних операцій додавання, віднімання та множення, ми отримали три нові масиви, які представляють результати цих операцій. Це показує, як можна використовувати NumPy для векторизованих обчислень, що значно спрощує роботу з даними в порівнянні з традиційними циклами в Python. 

26.(6)Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 10 до 100 та  
знайдіть їх добуток.

In [5]:
import numpy as np

# Створюємо дві матриці 4x4 з випадковими цілими числами від 10 до 100
matrix1 = np.random.randint(10, 101, size=(4, 4))
matrix2 = np.random.randint(10, 101, size=(4, 4))

# Виводимо матриці
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Обчислюємо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо результат
print("\nProduct of Matrix 1 and Matrix 2:")
print(product)

Matrix 1:
[[39 13 18 73]
 [66 54 44 53]
 [30 71 55 83]
 [31 34 23 35]]

Matrix 2:
[[75 71 86 85]
 [26 54 77 42]
 [38 75 98 86]
 [54 13 93 98]]

Product of Matrix 1 and Matrix 2:
[[ 7889  5770 12908 12563]
 [10888 11591 19075 16856]
 [10668 11168 21156 18396]
 [ 5973  6217 10793  9471]]


Висновок:
У цьому завданні ми створили дві матриці розміром 4x4, заповнені випадковими цілими числами в діапазоні від 10 до 100.Використовуючи функцію np.random.randint, ми змогли генерувати випадкові числа для заповнення матриць. Потім, для обчислення добутку цих матриць, ми скористалися функцією np.dot, що реалізує матричне множення. 

26.(7)Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами  
в діапазоні від 1 до 5 та перемножте їх між собою.

In [6]:
import numpy as np

# Створюємо матрицю A розміром 3x2 з випадковими цілими числами від 1 до 5
matrix_A = np.random.randint(1, 6, size=(3, 2))

# Створюємо матрицю B розміром 2x4 з випадковими цілими числами від 1 до 5
matrix_B = np.random.randint(1, 6, size=(2, 4))

# Виводимо матриці
print("Matrix A (3x2):")
print(matrix_A)
print("\nMatrix B (2x4):")
print(matrix_B)

# Обчислюємо добуток матриць A і B
product = np.dot(matrix_A, matrix_B)

# Виводимо результат
print("\nProduct of Matrix A and Matrix B:")
print(product)

Matrix A (3x2):
[[3 1]
 [5 2]
 [5 5]]

Matrix B (2x4):
[[5 1 2 5]
 [2 5 2 3]]

Product of Matrix A and Matrix B:
[[17  8  8 18]
 [29 15 14 31]
 [35 30 20 40]]


Висновок:
У данному завданні ми створили дві матриці: перша матриця розміром 3x2, а друга — 2x4, заповнені випадковими цілими числами в діапазоні від 1 до 5. Використовуючи функцію np.random.randint, ми змогли генерувати випадкові числа для заповнення матриць.

26.(8)Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні  
від 1 до 12 та знайдіть її обернену матрицю.

In [7]:
import numpy as np

# Створюємо матрицю розміром 3x3 з випадковими цілими числами від 1 до 12
matrix = np.random.randint(1, 13, size=(3, 3))

# Виводимо початкову матрицю
print("Original Matrix (3x3):")
print(matrix)

# Перевіряємо, чи є матриця оберненою (перевірка на детермінант)
determinant = np.linalg.det(matrix)

if determinant != 0:
    # Обчислюємо обернену матрицю
    inverse_matrix = np.linalg.inv(matrix)
    # Виводимо обернену матрицю
    print("\nInverse Matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is singular and does not have an inverse.")

Original Matrix (3x3):
[[ 9  9 11]
 [ 3  7  7]
 [ 4  5 12]]

Inverse Matrix:
[[ 0.21681416 -0.23451327 -0.0619469 ]
 [-0.03539823  0.28318584 -0.13274336]
 [-0.05752212 -0.03982301  0.15929204]]


Висновок: У цьому  завданні ми створили матрицю розміром 3x3, заповнену випадковими цілими числами в діапазоні від 1 до 12. Використовуючи функцію np.random.randint, ми змогли генерувати випадкові числа для заповнення матриці.

26.(9)Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні  
від 0 до 1 та транспонуйте її.

In [8]:
import numpy as np

# Створюємо матрицю розміром 4x4 з випадковими цілими числами 0 або 1
matrix = np.random.randint(0, 2, size=(4, 4))

# Виводимо початкову матрицю
print("Original Matrix (4x4):")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = matrix.T

# Виводимо транспоновану матрицю
print("\nTransposed Matrix:")
print(transposed_matrix)

Original Matrix (4x4):
[[0 0 0 1]
 [0 1 1 1]
 [0 1 1 0]
 [1 0 1 1]]

Transposed Matrix:
[[0 0 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 1 0 1]]


26.(10)Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю  
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними  
числами від 0 до 1, та знайдіть добуток матриці на вектор.

In [9]:
import numpy as np

# Створюємо матрицю розміром 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор розміром 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=(4, 1))

# Виводимо матрицю і вектор
print("Matrix (3x4):")
print(matrix)
print("\nVector (4x1):")
print(vector)

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результат
print("\nProduct of Matrix and Vector:")
print(product)

Matrix (3x4):
[[9 2 3 3]
 [3 5 6 1]
 [3 5 3 1]]

Vector (4x1):
[[0.60797877]
 [0.23081594]
 [0.93116481]
 [0.82457631]]

Product of Matrix and Vector:
[[11.20066417]
 [ 9.3895812 ]
 [ 6.59608676]]


26.(11)Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю  
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в  
діапазоні від 1 до 10, та знайдіть добуток матриці на вектор.

In [10]:
import numpy as np

# Створюємо матрицю розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(2, 3))

# Створюємо вектор розміром 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Виводимо матрицю і вектор
print("Matrix (2x3):")
print(matrix)
print("\nVector (3x1):")
print(vector)

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результат
print("\nProduct of Matrix and Vector:")
print(product)

Matrix (2x3):
[[0.39918459 0.92287145 0.76480498]
 [0.64649452 0.3221654  0.53410689]]

Vector (3x1):
[[8]
 [2]
 [2]]

Product of Matrix and Vector:
[[6.5688296 ]
 [6.88450075]]


26.(12)Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в  
діапазоні від 1 до 3та знайдіть добуток всіх елементів обох матриць.

In [11]:
import numpy as np

# Створюємо першу матрицю розміром 3x3 з випадковими цілими числами від 1 до 3
matrix1 = np.random.randint(1, 4, size=(3, 3))

# Створюємо другу матрицю розміром 3x3 з випадковими цілими числами від 1 до 3
matrix2 = np.random.randint(1, 4, size=(3, 3))

# Виводимо обидві матриці
print("Matrix 1 (3x3):")
print(matrix1)
print("\nMatrix 2 (3x3):")
print(matrix2)

# Обчислюємо добуток всіх елементів обох матриць
product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

# Виводимо результати
print("\nProduct of all elements in Matrix 1:")
print(product_matrix1)
print("\nProduct of all elements in Matrix 2:")
print(product_matrix2)

# Обчислюємо загальний добуток обох матриць
total_product = product_matrix1 * product_matrix2

print("\nTotal Product of all elements in both matrices:")
print(total_product)

Matrix 1 (3x3):
[[2 2 2]
 [1 2 2]
 [3 3 3]]

Matrix 2 (3x3):
[[1 3 1]
 [1 1 3]
 [2 1 3]]

Product of all elements in Matrix 1:
864

Product of all elements in Matrix 2:
54

Total Product of all elements in both matrices:
46656


26.(13)Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в  
діапазоні від -5 до 5 та знайдіть добуток їх елементів.

In [12]:
import numpy as np

# Створюємо першу матрицю розміром 3x3 з випадковими цілими числами від -5 до 5
matrix1 = np.random.randint(-5, 6, size=(3, 3))

# Створюємо другу матрицю розміром 3x3 з випадковими цілими числами від -5 до 5
matrix2 = np.random.randint(-5, 6, size=(3, 3))

# Виводимо обидві матриці
print("Matrix 1 (3x3):")
print(matrix1)
print("\nMatrix 2 (3x3):")
print(matrix2)

# Обчислюємо добуток всіх елементів обох матриць
product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

# Виводимо результати
print("\nProduct of all elements in Matrix 1:")
print(product_matrix1)
print("\nProduct of all elements in Matrix 2:")
print(product_matrix2)

# Обчислюємо загальний добуток елементів обох матриць
total_product = product_matrix1 * product_matrix2

print("\nTotal Product of all elements in both matrices:")
print(total_product)

Matrix 1 (3x3):
[[-1  5  5]
 [ 3  3 -3]
 [ 3  0 -3]]

Matrix 2 (3x3):
[[ 0  1 -4]
 [ 2 -2 -4]
 [-3  4  1]]

Product of all elements in Matrix 1:
0

Product of all elements in Matrix 2:
0

Total Product of all elements in both matrices:
0


26.(14)Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні  
від 1 до 10 та знайдіть середнє значення елементів на головній діагоналі.

In [13]:
import numpy as np

# Створюємо матрицю розміром 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Виводимо матрицю
print("Matrix (3x3):")
print(matrix)

# Отримуємо елементи на головній діагоналі
diagonal_elements = np.diag(matrix)

# Обчислюємо середнє значення елементів на головній діагоналі
mean_diagonal = np.mean(diagonal_elements)

# Виводимо результат
print("\nElements on the main diagonal:")
print(diagonal_elements)
print("\nMean value of the elements on the main diagonal:")
print(mean_diagonal)

Matrix (3x3):
[[7 2 4]
 [6 5 2]
 [3 6 9]]

Elements on the main diagonal:
[7 5 9]

Mean value of the elements on the main diagonal:
7.0


26.(15)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в  
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найменший елемент у  
кожному стовпці матриці.

In [14]:
import numpy as np

# Створюємо матрицю розміром 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, size=(3, 3))

# Виводимо матрицю
print("Matrix (3x3):")
print(matrix)

# Знаходимо найменший елемент у кожному стовпці
min_elements = np.min(matrix, axis=0)

# Перетворюємо вектор у вектор-стовпчик
min_vector_column = min_elements.reshape(-1, 1)

# Виводимо результати
print("\nMinimum elements in each column:")
print(min_elements)
print("\nColumn vector of minimum elements:")
print(min_vector_column)

Matrix (3x3):
[[-0.81580538 -0.83736295 -0.64488646]
 [-0.08730343 -0.31825397  0.18491115]
 [ 0.1562069  -0.22701871  0.76867336]]

Minimum elements in each column:
[-0.81580538 -0.83736295 -0.64488646]

Column vector of minimum elements:
[[-0.81580538]
 [-0.83736295]
 [-0.64488646]]


Загальний висновок по роботі:У процесі виконання завдань було продемонстровано, як використовувати бібліотеку NumPy для створення та обробки матриць в Python.Протягом роботи було показано, як можна генерувати випадкові дані, а також отримувати з них статистичну інформацію, що може бути корисним у різних галузях, таких як машинне навчання, статистика, фінансовий аналіз тощо.Завдання демонструють, як можна змінювати розміри матриць та діапазони значень, що дозволяє адаптувати код під різні сценарії та потреби. 